/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geust_house.myFrame;

import com.toedter.calendar.JDateChooser;
import geust_house.guesthouse.DataConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SIENGHORN
 */
public class frmCancelBooking extends javax.swing.JFrame {

    DataConnection data=new DataConnection();
    Statement stm;
    ResultSet res;
    PreparedStatement pst=null;
    Date cancelDate=null,dateIn=null,dateOut=null;
    Calendar c=Calendar.getInstance();
    SimpleDateFormat df= new SimpleDateFormat("YYYY-MM-DD HH-mm-ss");
    int book_id=0,room_id,cus_id;
    float price=0;
    public frmCancelBooking() {
        try {
            initComponents();
            
            cancelDate=c.getTime();
            CancelDate.setDate(cancelDate);
            //get BookIdn or BookNum
            pst=data.getConnectio().prepareStatement(SqlConfigString.SELECT_BOOKID_FORCHECKIN);
            res=pst.executeQuery();
            while(res.next()){
                cmbBookNum.addItem(res.getInt(1)+"");
            }
            res.close();
           
        } catch (SQLException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DateFrom = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        cmbBookNum = new javax.swing.JComboBox<>();
        cmbRoom = new javax.swing.JComboBox<>();
        ChangeRoom = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        CancelDate = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        DateTo = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Change Room");

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(42, 42, 42))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rate information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Room Num: ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("From Date");

        DateFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateFromPropertyChange(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Book Num:");

        jLabel3.setText("Date : ");

        lblDate.setText("   ");

        cmbBookNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbBookNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Book Num" }));
        cmbBookNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbBookNumFocusLost(evt);
            }
        });
        cmbBookNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBookNumMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbBookNumMouseReleased(evt);
            }
        });
        cmbBookNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBookNumActionPerformed(evt);
            }
        });

        cmbRoom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room" }));
        cmbRoom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbRoomFocusLost(evt);
            }
        });
        cmbRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbRoomMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbRoomMouseReleased(evt);
            }
        });
        cmbRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoomActionPerformed(evt);
            }
        });

        ChangeRoom.setBackground(new java.awt.Color(0, 102, 102));
        ChangeRoom.setText("OK ");
        ChangeRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeRoomActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        CancelDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CancelDatePropertyChange(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("To Date");

        DateTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateToPropertyChange(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Price : ");

        txtPrice.setText(" ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3)
                                .addGap(47, 47, 47)
                                .addComponent(CancelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(cmbBookNum, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbRoom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                            .addComponent(txtPrice))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(ChangeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblDate))
                    .addComponent(CancelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbBookNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(DateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(DateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangeRoom)
                    .addComponent(jButton2))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void cmbBookNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBookNumMouseClicked

    }//GEN-LAST:event_cmbBookNumMouseClicked

    private void cmbBookNumMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBookNumMouseReleased

    }//GEN-LAST:event_cmbBookNumMouseReleased

    private void cmbRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbRoomMouseClicked
        
    }//GEN-LAST:event_cmbRoomMouseClicked

    private void cmbRoomMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbRoomMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoomMouseReleased

    private void cmbRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoomActionPerformed

    private void ChangeRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeRoomActionPerformed
        try {
            //duration of cancel book
            int diff=(int) ((DateTo.getDate().getTime()-DateFrom.getDate().getTime())/(1000*3600*24));
            JOptionPane.showMessageDialog(this,DateTo.getDate().getTime());
            JOptionPane.showMessageDialog(this,DateFrom.getDate().getTime());
            JOptionPane.showMessageDialog(this,diff);
            //insert into cancel booking
            pst=data.getConnectio().prepareStatement(SqlConfigString.INSERT_INTO_CANCELBOOK);
            pst.setString(1,df.format(cancelDate));
            pst.setInt(2, 1);
            pst.setInt(3, book_id);
            pst.setInt(4,cus_id);
             JOptionPane.showMessageDialog(this,df.format(cancelDate)+ book_id+cus_id);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(this,"insert into cancel book success");
            //get cancel book id
            int cancel_book_id=0;
            pst=data.getConnectio().prepareStatement(SqlConfigString.MAX_ID_CANCELBOOK);
            res=pst.executeQuery();
            while(res.next()){
                cancel_book_id=res.getInt(1);
            }
            res.close();
            //if the customer call to cancel b4 book check in date the refund will give 
            if(cancelDate.compareTo(dateIn)>=0){
                price=0;
            }
            //insert into cancel book detail
            pst=data.getConnectio().prepareStatement(SqlConfigString.INSERT_INTO_CANCELBOOK_DETAIL);
            pst.setInt(1, cancel_book_id);
            pst.setInt(2, room_id);
            pst.setInt(3, diff);
            pst.setFloat(4,price);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(this,"insert into cancel book detail success");
            //Update status in Booking
            SimpleDateFormat dc=new SimpleDateFormat("YYYY-MM-DD");
            if(dc.format(DateFrom.getDate()).compareTo(dateIn.toString())==0 && dc.format(DateTo.getDate()).compareTo(dateOut.toString())==0){
                pst=data.getConnectio().prepareStatement(SqlConfigString.UPDATE_STATUS_BOOK_DETAIL);
                pst.setString(1,"Cancel Booking");
                pst.setInt(2, book_id);
                pst.execute();
                pst.close();
                JOptionPane.showMessageDialog(this,"Update Sucessfully");
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
    }//GEN-LAST:event_ChangeRoomActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CancelDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CancelDatePropertyChange
       if("date".equals(evt.getPropertyName())){
           JDateChooser cDate=(JDateChooser) evt.getSource();
           cancelDate=cDate.getDate();
       }
    }//GEN-LAST:event_CancelDatePropertyChange

    private void cmbBookNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBookNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBookNumActionPerformed

    private void DateToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateToPropertyChange
       if("date".equals(evt.getPropertyName())){
           try{
               JDateChooser dateTo=(JDateChooser) evt.getSource();
              String dateToFormat=new SimpleDateFormat("YYYY-MM-DD").format(dateTo.getDate());
              if(dateToFormat.compareTo(dateOut.toString())>0||dateToFormat.compareTo(dateIn.toString())<=0){
                  JOptionPane.showMessageDialog(this,"Out of book date : "+dateIn+" - "+dateOut);
                        dateTo.setDate(null);
              }

           }catch(Exception ex){}
       }
    }//GEN-LAST:event_DateToPropertyChange

    private void DateFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateFromPropertyChange
        if("date".equals(evt.getPropertyName())){ 
       
                try{
                    JDateChooser dateFrom= (JDateChooser) evt.getSource();
                    if(dateFrom.getDate().compareTo(dateIn)<0 ||dateFrom.getDate().compareTo(dateOut)>=0){
                       JOptionPane.showMessageDialog(this,"Out of book date : "+dateIn+" - "+dateOut);
                        dateFrom.setDate(null);
                    }
                    
                }catch(Exception ex){}
                

           
           
           
       }
    }//GEN-LAST:event_DateFromPropertyChange

    private void cmbBookNumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbBookNumFocusLost
        try {
            book_id=Integer.parseInt(cmbBookNum.getSelectedItem().toString());
            //get the room id of the book id
            pst=data.getConnectio().prepareStatement(SqlConfigString.SELECT_ROOM_CHECKIN);
            pst.setInt(1,book_id);
            res=pst.executeQuery();
            while(res.next()){
                cmbRoom.addItem(res.getInt(1)+"");
            }
            res.close();
        } catch (SQLException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbBookNumFocusLost

    private void cmbRoomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbRoomFocusLost
        try {
            room_id=Integer.parseInt(cmbRoom.getSelectedItem().toString());
            pst=data.getConnectio().prepareStatement(SqlConfigString.SELECT_BOOK_PRICE_OF_AROOM);
            pst.setInt(1,room_id);
            res=pst.executeQuery();
            while(res.next()){
                price=res.getFloat(1);
                txtPrice.setText(new DecimalFormat("$0.00").format(price));
            }
            res.close();
            //get the book_check_in date and book checkeout date
                pst=data.getConnectio().prepareStatement(SqlConfigString.SELECT_DATE_OF_BOOKING);
                pst.setInt(1,book_id);
                res=pst.executeQuery();
                while(res.next()){
                    dateIn=res.getDate(1);
                    dateOut=res.getDate(2);
                    cus_id=res.getInt(3);
                }
                res.close();
                JOptionPane.showMessageDialog(this, dateIn+"   "+dateOut);
        } catch (SQLException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(frmCancelBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmbRoomFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCancelBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCancelBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCancelBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCancelBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCancelBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CancelDate;
    private javax.swing.JButton ChangeRoom;
    private com.toedter.calendar.JDateChooser DateFrom;
    private com.toedter.calendar.JDateChooser DateTo;
    private javax.swing.JComboBox<String> cmbBookNum;
    private javax.swing.JComboBox<String> cmbRoom;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
